import React, { Suspense, lazy, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, ArrowLeft, RotateCcw, Play, Pause, Plus, Minus, Maximize, Trophy, Flag, CarFront, GitBranch, BookOpen, X, Check, Sparkles, VolumeX, Compass, ChevronRight } from 'lucide-react';
import City from './City.jsx';
import { solve } from './engine.js';
import { evaluateAllocation, starsFor } from './game.js';
import './styles.css';
import './game.css';
const Research=lazy(()=>import('./Research.jsx'));
const chapters=[['01','THE COMMUTE','Nash Equilibrium'],['02','THE SHORTCUT','Braess’s Paradox'],['03','THE BIG PICTURE','System Optimal']];
function loadBest(){try{const n=Number(localStorage.getItem('flowstate-game-best'));return Number.isInteger(n)&&n>=0&&n<=500?n:0;}catch{return 0;}}
function App(){
 const [round,setRound]=useState(0),[choice,setChoice]=useState(null),[settled,setSettled]=useState(false),[prediction,setPrediction]=useState(null),[upper,setUpper]=useState(5),[hybrid,setHybrid]=useState(40),[feedback,setFeedback]=useState(null),[won,setWon]=useState(false),[playing,setPlaying]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches),[speed,setSpeed]=useState(1),[raceId,setRaceId]=useState(0),[arrived,setArrived]=useState(false),[cameraAction,setCameraAction]=useState(null),[help,setHelp]=useState(false),[research,setResearch]=useState(false),[best,setBest]=useState(loadBest);
 const baseline=useMemo(()=>solve(50),[]),nash=useMemo(()=>solve(50,true),[]),optimal=useMemo(()=>solve(50,true,'cooperative'),[]);
 const allocation=useMemo(()=>evaluateAllocation(upper,hybrid),[upper,hybrid]);
 const result=round===0?(settled?baseline:evaluateAllocation(choice==='Lower'?34:35,0,50,false)):round===1?(prediction?nash:baseline):allocation;
 const playerRoute=round===2?(hybrid>upper&&hybrid>50-upper-hybrid?'Hybrid':upper>=50-upper-hybrid?'Upper':'Lower'):round===1&&prediction?'Hybrid':choice||'Upper';
 const points=(choice==='Lower'?100:choice?50:0)+(prediction==='slower'?100:0)+(won?300:0);
 function drive(){setRaceId(id=>id+1);setPlaying(true);setArrived(false);}
 function choose(name){setChoice(name);drive();}
 function next(){setRound(r=>Math.min(2,r+1));setArrived(false);if(round===0)setSettled(true);}
 function restart(){setRound(0);setChoice(null);setSettled(false);setPrediction(null);setUpper(5);setHybrid(40);setFeedback(null);setWon(false);setArrived(false);setRaceId(0);setSpeed(1);setPlaying(!window.matchMedia('(prefers-reduced-motion: reduce)').matches);setCameraAction({action:'reset'});}
 function checkPlan(){const stars=starsFor(allocation.average,optimal.average);setFeedback(stars);drive();if(stars===3){setWon(true);const total=(choice==='Lower'?100:50)+(prediction==='slower'?100:0)+300;const record=Math.max(best,total);setBest(record);try{localStorage.setItem('flowstate-game-best',String(record));}catch{}}}
 function changeUpper(v){setUpper(v);if(v+hybrid>50)setHybrid(50-v);setFeedback(null);}
 function changeHybrid(v){setHybrid(v);if(v+upper>50)setUpper(50-v);setFeedback(null);}
 const cam=action=>setCameraAction({action});
 return <div className="game-app"><header className="game-header"><a className="game-brand" href="#" onClick={e=>{e.preventDefault();restart();}}><span><GitBranch size={23}/></span>flowstate<b>.</b><em>THE GAME</em></a><div className="game-header-center"><span className="online-dot"/> A CITY. 50 DRIVERS. ONE BIG QUESTION.</div><div className="header-actions"><button onClick={()=>setResearch(true)}><BookOpen size={16}/><span>Research lab</span></button><button onClick={()=>setHelp(true)} aria-label="How to play">?</button></div></header>
 <main className="game-main"><section className="game-intro"><div><div className="game-kicker"><span/> AN INTERACTIVE 3D GAME THEORY EXPERIENCE</div><h1>Beat the <span>traffic.</span></h1><p>Think like a driver. Play like a planner. Change the way a city moves.</p></div><div className="score-actions"><div className="score-pill"><Trophy size={22}/><div><strong>{String(points).padStart(3,'0')}</strong><span>YOUR SCORE</span></div><i/><div><strong>{best||'—'}</strong><span>PERSONAL BEST</span></div></div><button className="restart-anytime" onClick={restart} title="Start over from mission 1"><RotateCcw size={15}/> Restart game</button></div></section>
 <div className="chapter-track">{chapters.map(([num,title,concept],i)=><div key={num} className={`chapter ${round===i?'active':''} ${round>i||won?'complete':''}`}><span className="chapter-index">{round>i||won?<Check size={17}/>:num}</span><div><small>{title}</small><strong>{concept}</strong></div>{i<2&&<ChevronRight className="chapter-chevron" size={18}/>}</div>)}</div>
 <section className="game-stage"><div className="city-wrap"><City result={result} playerRoute={playerRoute} raceId={raceId} playing={playing} speed={speed} cameraAction={cameraAction} onArrive={()=>setArrived(true)}/><div className="city-top"><span className="district-tag"><span/> FLOWSTATE CITY <small>EST. 2026</small></span><span className="city-weather">☀ <span>GOLDEN HOUR</span></span></div><div className="floating-label"><span className="yellow-dot"/> YOUR CAR IS GOLD <span className="label-divider"/> {playing?'CITY IN MOTION':'CITY PAUSED'}</div>
 <div className="camera-controls"><button aria-label="Zoom in" onClick={()=>cam('in')}><Plus size={17}/></button><button aria-label="Zoom out" onClick={()=>cam('out')}><Minus size={17}/></button><span/><button aria-label="Rotate camera left" onClick={()=>cam('left')}><ArrowLeft size={16}/></button><button aria-label="Rotate camera right" onClick={()=>cam('right')}><ArrowRight size={16}/></button><span/><button aria-label="Top view" onClick={()=>cam('top')}><Compass size={17}/></button><button aria-label="Reset camera" onClick={()=>cam('reset')}><Maximize size={16}/></button></div>
 <div className="city-bottom"><div className="city-legend"><span><i className="upper-color"/>Upper</span><span><i className="lower-color"/>Lower</span>{result.braess&&<span><i className="hybrid-color"/>Hybrid</span>}</div><div className="city-playback"><button aria-label={playing?'Pause city':'Play city'} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><select aria-label="Animation speed" value={speed} onChange={e=>setSpeed(+e.target.value)}><option value=".5">0.5×</option><option value="1">1×</option><option value="2">2×</option></select></div></div><span className="orbit-instruction">DRAG TO ORBIT · SCROLL TO ZOOM</span></div>
 <aside className="mission-panel"><div className="mission-topline"><span>MISSION 0{round+1}</span><span>{won?'COMPLETED':`0${round+1} / 03`}</span></div>
 {round===0&&<><div className="mission-icon"><CarFront size={26}/></div><h2>Your route.<br/>Everyone’s rush hour.</h2><p className="mission-description">50 drivers. Two ways across the city. The upper route is busy. Can you find a quicker commute?</p><div className="mission-objective"><Flag size={17}/><span>Choose the fastest route from A to D.</span></div><div className="route-choices">{['Upper','Lower'].map((name,i)=><button key={name} className={`route-choice ${choice===name?'chosen':''}`} disabled={!!choice} onClick={()=>choose(name)}><span className={`route-symbol ${i?'lower-color':'upper-color'}`}><GitBranch size={20}/></span><span><strong>{name} route</strong><small>A → {i?'C':'B'} → D</small></span><b>{i?'60':'80'}<small> min</small></b>{choice===name?<Check size={16}/>:<ArrowRight size={16}/>}</button>)}</div>
 {choice&&<div className="mission-feedback" role="status"><strong>{choice==='Lower'?'Good instinct. You found the faster route!':'The upper route is crowded.'} <span>+{choice==='Lower'?100:50} pts</span></strong><p>{settled?'Other drivers switched too. Both routes now take 70 minutes. No driver can improve by switching alone: Nash Equilibrium (Wardrop UE).':`Your choice gives a ${result.times[choice].toFixed(1)}-minute journey. But the other drivers also want the quickest route. Watch what happens when everyone adapts.`}</p></div>}
 <div className="mission-action">{!choice?<div className="choose-prompt">Pick a route to start your journey <ArrowRight size={15}/></div>:!settled?<button className="game-primary" onClick={()=>{setSettled(true);drive();}}>Let everyone adapt <ArrowRight size={17}/></button>:<button className="game-primary" onClick={next}>Next: the tempting shortcut <ArrowRight size={17}/></button>}</div><div className="concept-note"><span>YOU’LL DISCOVER</span><strong>Nash Equilibrium <small>(Wardrop UE)</small></strong></div></>}
 {round===1&&<><div className="mission-icon amber"><GitBranch size={26}/></div><h2>A new road.<br/>A better commute?</h2><p className="mission-description">The city wants to open the Braess edge: a nearly free shortcut between B and C. Make your prediction before it opens.</p><div className="mission-objective"><Flag size={17}/><span>Will the average journey get faster or slower?</span></div><div className="prediction-options">{[['faster','Faster','More roads, less traffic?'],['slower','Slower','There might be a catch…']].map(([v,label,sub])=><button key={v} disabled={!!prediction} className={prediction===v?'chosen':''} onClick={()=>{setPrediction(v);drive();}}><strong>{label} <ArrowRight size={17}/></strong><small>{sub}</small></button>)}</div>
 {prediction&&<div className="mission-feedback amber-feedback" role="status"><strong>{prediction==='slower'?'You saw the trap. +100 pts':'Surprise: the new road makes it worse.'}</strong><div className="before-after"><span>70<small>BEFORE · MIN</small></span><ArrowRight size={23}/><span>90<small>AFTER · MIN</small></span></div><p>At Nash Equilibrium, 40 drivers take the hybrid route and overload AB and CD. Average travel time rises by 20 minutes. This is <b>Braess’s Paradox</b>.</p></div>}
 <div className="mission-action">{prediction?<button className="game-primary" onClick={next}>Your turn to fix the city <ArrowRight size={17}/></button>:<div className="choose-prompt">Your prediction unlocks the shortcut.</div>}</div><div className="concept-note"><span>YOU’LL DISCOVER</span><strong>Braess’s Paradox</strong></div></>}
 {round===2&&!won&&<><div className="mission-icon"><Flag size={26}/></div><h2>Now you’re<br/>in the driver’s seat.</h2><p className="mission-description">You’re the city planner. Assign all 50 drivers to routes. The Braess edge stays open—using it is your choice.</p><div className="mission-objective"><Trophy size={18}/><span>Reach <b>70.0 min</b> to earn three stars.</span></div><div className="allocation"><label htmlFor="upper"><span><i className="upper-color"/>Upper · A → B → D</span><b>{upper} cars</b></label><input id="upper" aria-label="Upper route drivers" type="range" min="0" max="50" value={upper} onChange={e=>changeUpper(+e.target.value)}/><label htmlFor="hybrid"><span><i className="hybrid-color"/>Hybrid · A → B → C → D</span><b>{hybrid} cars</b></label><input id="hybrid" aria-label="Hybrid route drivers" type="range" min="0" max="50" value={hybrid} onChange={e=>changeHybrid(+e.target.value)}/><div className="remaining-drivers"><span><i className="lower-color"/>Lower · A → C → D</span><b>{50-upper-hybrid} cars</b></div><small>Remaining drivers take the lower route automatically.</small></div><div className="plan-meter"><span>CITY AVERAGE</span><strong>{allocation.average.toFixed(1)} <small>min</small></strong><div><span style={{width:`${Math.min(100,70/allocation.average*100)}%`}}/></div></div>{feedback!==null&&<div className="mission-feedback" role="status"><strong>{'★'.repeat(feedback)}{'☆'.repeat(3-feedback)} Keep experimenting.</strong><p>{hybrid>0?'The free shortcut still loads both congested roads. Try reducing hybrid traffic.':'The shortcut is empty. Try sharing drivers evenly between the upper and lower routes.'}</p></div>}<div className="mission-action"><button className="game-primary" onClick={checkPlan}>Test my traffic plan <Play size={16}/></button></div><div className="concept-note"><span>YOU’LL DISCOVER</span><strong>System Optimal <small>(Cooperative Routing)</small></strong></div></>}
 {won&&<div className="victory"><div className="victory-stars">★ ★ ★</div><div className="trophy-circle"><Trophy size={45}/></div><div className="game-kicker">CITY SAVED. LESSON LEARNED.</div><h2>You beat<br/>the traffic.</h2><p>You found System Optimal routing: 25 drivers on each outer route, none on the shortcut.</p><div className="win-stat"><strong>20 <small>min</small></strong><span>SAVED PER DRIVER</span></div><div className="win-details"><span>Price of Anarchy</span><b>{(nash.average/optimal.average).toFixed(2)}×</b><span>Your final score</span><b>{points} pts</b></div><button className="game-primary" onClick={restart}>Play again <RotateCcw size={17}/></button><button className="game-secondary" onClick={()=>setResearch(true)}>Explore the research <ArrowRight size={15}/></button></div>}
 </aside></section>
 <section className="game-telemetry"><div><span><CarFront size={16}/> CITY POPULATION</span><strong>50 <small>drivers</small></strong></div><div><span><Compass size={16}/> AVERAGE JOURNEY</span><strong>{result.average.toFixed(1)} <small>minutes</small></strong></div><div><span><GitBranch size={16}/> BRAESS EDGE</span><strong className={result.braess?'edge-open':''}>{result.braess?'Open':'Closed'}<small>B → C</small></strong></div><div><span><Flag size={16}/> YOUR JOURNEY</span><strong>{arrived?'Arrived':raceId>0?'On the road':'Ready to go'}<small>{raceId>0?playerRoute+' route':'Choose your route'}</small></strong></div></section>
 <div className="game-footnote"><span><Sparkles size={14}/> Real game theory. A miniature world of consequences.</span><span>Journey times are modelled minutes · animation is accelerated</span><button onClick={restart}><RotateCcw size={13}/> Restart game</button></div>
 </main>
 {help&&<div className="game-modal-backdrop" onClick={()=>setHelp(false)}><section className="game-help" role="dialog" aria-modal="true" aria-labelledby="help-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setHelp(false);if(e.key==='Tab'){e.preventDefault();e.currentTarget.querySelector('button').focus();}}}><button autoFocus className="close-help" aria-label="Close instructions" onClick={()=>setHelp(false)}><X size={21}/></button><div className="game-kicker">THREE MISSIONS. ONE CITY.</div><h2 id="help-title">How to beat the traffic</h2><p><b>01 · Choose a route.</b> The quieter route earns 100 points; the other earns 50 exploration points. Let other drivers adapt to discover Nash Equilibrium.</p><p><b>02 · Predict the shortcut.</b> A correct prediction earns 100 points. Open the Braess edge and see the result at the same demand.</p><p><b>03 · Plan the city.</b> Allocate 50 drivers. A plan within 0.1 minutes of the optimum earns three stars and 300 points. Within 5 minutes earns two stars; within 15 earns one. Keep trying until you earn three.</p><p>Drag the city to orbit, scroll to zoom, or use the camera buttons. Your car is gold. Pause and speed controls affect the animation, not the calculations.</p><small>AB and CD take approximately one minute per driver; AC and BD take 45 minutes; BC is nearly free. The shortcut’s effect depends on demand. This mission uses 50 drivers. No sound or driving controls are required.</small></section></div>}
 {research&&<div className="research-overlay"><div className="research-back"><button onClick={()=>setResearch(false)}><ArrowLeft size={17}/> Back to the 3D game</button><span>THE SCIENCE BEHIND YOUR DECISIONS</span></div><div className="game-research"><Suspense fallback={<p className="research-loading">Loading research lab…</p>}><Research/></Suspense></div></div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
