import React, { useMemo, useRef, useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowLeft, Play, Pause, RotateCcw, MoveUpRight, Route, SlidersHorizontal, GitBranch, X, Download, Activity, Clock3, Users, Sparkles, BookOpen, ChevronRight, Check, Cpu } from 'lucide-react';
import { solve, scenarios, train, cost, BASE } from './engine.js';
import './styles.css';

function IconButton({label,children,...props}) {return <button className="icon-button" aria-label={label} {...props}>{children}</button>;}
function LineChart({ series, labels = ['10', '45', '80', '115', '150'], yLabel = 'Travel time · min' }) {
  const values=series.flatMap(s=>s.values), min=Math.floor(Math.min(...values)*.8), max=Math.ceil(Math.max(...values)*1.1), span=Math.max(max-min,1);
  return <div className="chart"><span className="chart-axis">{yLabel}</span><svg viewBox="0 0 600 230" role="img" aria-label={series.map(s=>`${s.name}: ${s.values.map(v=>v.toFixed(1)).join(', ')}`).join('; ')}>{[0,1,2,3].map(i=><g key={i}><line x1="40" y1={20+i*55} x2="580" y2={20+i*55} stroke="#e8ece9" strokeDasharray="4 4"/><text x="0" y={24+i*55}>{Math.round(max-i*span/3)}</text></g>)}{series.map(s=><polyline key={s.name} fill="none" stroke={s.color} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" points={s.values.map((v,i)=>`${40+i*540/Math.max(s.values.length-1,1)},${20+(max-v)*165/span}`).join(' ')}/>)}{labels.map((l,i)=><text key={i} x={40+i*540/Math.max(labels.length-1,1)} y="218" textAnchor="middle">{l}</text>)}</svg><div className="chart-legend">{series.map(s=><span key={s.name}><i style={{background:s.color}}/>{s.name}</span>)}</div></div>;
}
export default function Research() {
  const [tab,setTab]=useState('Insights'), [cars,setCars]=useState(50), [braess,setBraess]=useState(false), [episodes,setEpisodes]=useState(200), [training,setTraining]=useState(null), [busy,setBusy]=useState(false), [about,setAbout]=useState(false);
  const all=useMemo(()=>scenarios(cars),[cars]);
  const selfish=all.find(s=>s.braess===braess && s.mode==='selfish'), optimal=all.find(s=>s.braess===braess && s.mode==='cooperative');
  const curves=useMemo(()=>[false,true].map(b=>({name:b?'With Braess edge':'Without Braess edge',color:b?'#d5a159':'#3b8976',values:Array.from({length:29},(_,i)=>solve(10+i*5,b).average)})),[]);
  const exportData=()=>{const rows=['strategy,braess_edge,cars,average_minutes,total_car_minutes',...all.map(s=>`${s.mode === 'selfish' ? 'Nash Equilibrium (UE)' : 'System Optimal (SO)'},${s.braess},${s.cars},${s.average.toFixed(3)},${s.total.toFixed(3)}`)];const url=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='flowstate-scenarios.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <><header><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('Playground');}}><span className="brand-symbol"><GitBranch size={21}/></span>flowstate<span className="brand-dot">.</span></a><nav aria-label="Main navigation">{['Insights','Learning lab'].map(t=><button key={t} className={tab===t?'nav-active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><button className="header-link" onClick={()=>setAbout(true)}>The science behind it <ArrowUpRight size={15}/></button></header>
  <main><section className="research-controls"><label htmlFor="research-cars">Traffic volume: <b>{cars} drivers</b><input id="research-cars" type="range" min="10" max="150" value={cars} onChange={e=>setCars(+e.target.value)}/></label><label><input type="checkbox" checked={braess} onChange={e=>setBraess(e.target.checked)}/> Enable Braess edge (B → C)</label></section>
  {tab==='Insights' && <><div className="insights-grid"><section className="content-card"><div className="card-heading"><h3>Braess’s Paradox</h3><GitBranch size={19}/></div><p>Compare Nash Equilibrium (Wardrop UE) across traffic volumes. The shortcut helps at low demand, but can hurt as more drivers use it.</p><LineChart series={curves}/><div className="chart-caption">Number of drivers →</div></section><section className="content-card comparison"><div className="card-heading"><h3>Nash Equilibrium vs System Optimal</h3><span>{cars} DRIVERS</span></div><p>{braess?'With the Braess edge open':'Without the Braess edge'}, compare selfish (UE) and cooperative (SO) routing.</p>{[['Nash Equilibrium (UE)',selfish,'#d6aa65'],['System Optimal (SO)',optimal,'#3d8b77']].map(([label,s,c])=><div className="comparison-row" key={label}><div><span>{label}</span><strong>{s.average.toFixed(1)} min</strong></div><div className="comparison-track"><span style={{width:`${s.average/Math.max(selfish.average,optimal.average)*100}%`,background:c}}/></div></div>)}<div className="comparison-summary"><span>{Math.max(0,selfish.average-optimal.average).toFixed(1)} <small>minutes</small></span><p>saved per driver with System Optimal routing</p></div></section></div><section className="content-card scenario-card"><div className="card-heading"><h3>Four ways to move a city</h3><button className="text-button" onClick={exportData}><Download size={15}/> Export results</button></div><div className="table-wrap"><table><thead><tr><th>Routing strategy</th><th>Braess edge</th><th>Average journey</th><th>Total travel time</th><th>Nash Equilibrium</th></tr></thead><tbody>{all.map(s=><tr key={s.mode+ s.braess}><td>{s.mode==='selfish'?'Nash Equilibrium (UE)':'System Optimal (SO)'}</td><td><span className={`table-badge ${s.braess?'amber':''}`}>{s.braess?'Open':'Closed'}</span></td><td>{s.average.toFixed(1)} min</td><td>{s.total.toFixed(0)} car·min</td><td>{s.nash?'Reached':'Not at equilibrium'}</td></tr>)}</tbody></table></div></section></>}
  {tab==='Learning lab' && <section className="learning-grid"><div className="content-card learning-setup"><span className="lab-icon"><Cpu size={27}/></span><div className="eyebrow">REINFORCEMENT LEARNING</div><h2>A signal that<br/>learns by doing.</h2><p>A Q-learning agent favours one side of the network, observes the journey time, and updates its next choice.</p><label className="control-label" htmlFor="episodes">Training episodes <strong>{episodes}</strong></label><input id="episodes" type="range" min="50" max="500" step="50" value={episodes} onChange={e=>setEpisodes(+e.target.value)}/><p className="training-config">Current experiment: {cars} cars · Braess edge {braess?'open':'closed'}. Use the experiment controls above.</p><button className="primary" disabled={busy} onClick={()=>{setBusy(true);setTimeout(()=>{setTraining(train(cars,braess,episodes));setBusy(false);},50);}}><Play size={16}/>{busy?'Training…':training?'Train again':'Train the agent'}<ArrowRight size={17}/></button><small className="model-note">Teaching model: a 20% capacity boost is applied to AB or AC. AC has constant travel time, so boosting it has no effect.</small></div><div className="content-card"><div className="card-heading"><h3>Learning in motion</h3><span>{training?`${training.episodes} EPISODES`:'READY WHEN YOU ARE'}</span></div>{training?<><p>Completed with {training.cars} drivers and the Braess edge {training.braess?'open':'closed'}. Higher rewards mean shorter journeys.</p><LineChart yLabel="Reward · negative travel time" labels={['1',String(Math.round(training.episodes/2)),String(training.episodes)]} series={[{name:'10-episode moving average',color:'#3b8976',values:training.rewards.map((_,i)=>training.rewards.slice(Math.max(0,i-9),i+1).reduce((s,r)=>s+r,0)/Math.min(i+1,10))}]}/><h4>What the agent learned</h4><div className="table-wrap"><table><thead><tr><th>Congestion state</th><th>Favour upper</th><th>Favour lower</th></tr></thead><tbody>{training.q.map((q,i)=><tr key={i}><td>{['Low','Medium','High'][i]}</td><td>{q[0].toFixed(2)}</td><td>{q[1].toFixed(2)}</td></tr>)}</tbody></table></div><p className="model-note">Zero values can indicate unvisited states. Training is stochastic and does not guarantee a steadily improving curve.</p></>:<div className="empty-state"><Activity size={46}/><h3>Every good decision starts<br/>with a little exploration.</h3><p>Start training to see the reward curve<br/>and the agent’s learned preferences.</p></div>}</div></section>}
  <footer><a className="brand" href="#" onClick={e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'});}}>flowstate<span className="brand-dot">.</span></a><span>A little game theory. A different way to see the world.</span><span>BUILT FOR CURIOSITY <MoveUpRight size={13}/></span></footer></main>
  {about&&<div className="modal-backdrop" onClick={()=>setAbout(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="science-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setAbout(false);if(e.key==='Tab'){e.preventDefault();e.currentTarget.querySelector('button').focus();}}}><IconButton label="Close explanation" autoFocus onClick={()=>setAbout(false)}><X size={20}/></IconButton><div className="eyebrow">THE SCIENCE BEHIND IT</div><h2 id="science-title">When rational choices<br/>meet a shared road.</h2><h3>Nash Equilibrium (Wardrop UE)</h3><p>No driver can shorten their journey by switching routes alone. All used routes have approximately equal travel times.</p><h3>Braess’s Paradox</h3><p>A new shortcut can make everyone slower. At 50 drivers, compare the same network with and without the shortcut to see the effect.</p><h3>Cooperative Routing (System Optimal)</h3><p>A planner minimises the total time spent by all drivers. The price of anarchy is selfish total cost divided by optimal total cost.</p><h3>The network model</h3><p>AB and CD take approximately one minute per driver on the road. AC and BD take a fixed 45 minutes. BC takes approximately zero minutes. Assignments use 2,000 successive-average iterations.</p><small>Based on Wardrop (1952), Braess (1968), and the original project’s BPR cost model.</small></section></div>}
  </>;
}
function Metric({icon:Icon,label,value,unit,note}) {return <div className="metric"><div className="metric-label"><Icon size={15}/>{label}</div><div className="metric-value">{value}<span>{unit}</span></div><div className="metric-note">{note}</div></div>;}
